module.exports = {
	prompts: [ {text: "_____? There's an app for that."}, {text:"Why can't I sleep at night?"}, {text:"What's that smell?"}, {text: "I got 99 problems but _____ ain't one."}, {text: "Maybe she's born with it. Maybe it's ______"}, {text:"What's the next Happy Meal toy?"}, {text:"Anthropologists have recently discovered a primitive tribe that worships _____."}, {text: "it's a pity that kids these days are getting involved with _____."}, {text:"During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____."}, { text: "Alternative medicine is now embracing the curative powers of _____."}, {text: "What's that sound?"}, {text: "What ended my last relationship?"}, {text: "I drink to forget ______."}, { text: "I'm sorry Professor, but I couldn't complete my homework because of ______"}, {text: "What is Batman's guilty pleasure?"}, {text: "This is the way the world ends. Not with a bang but with ______."}, {text: "What's a girl's best friend?"}, {text: "TSA guidelines now prohibit _____ on airplanes."}, {text: "______. That's how I want to die."}, {text: "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time."}, {text: "Bernie Sanders enjoys ______ at 2am."}, {text: "BILLY MAYS HERE FOR ______."}, {text:"War! What is it good for?"}, {text:"During sex, I like to think about _____."}, {text:"What are my parents hiding from me?"}, {text:"What will always get you laid?"}, {text:"In L.A. County Jail, word is you can trade 200 cigarettes for _____."}, {text:"What did I bring back from Mexico?"}, {text:"What don't you want to find in your Chinese food?"}, {text:"What will I bring back in time to convince people that I am a powerful wizard?"}, {text:"How am I maintaining my relationship status?"}, {text:"_____. It's a trap!"}, {text:"Coming to Broadway this season, _____:The Musical."}, {text:"While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____."}, {text:"After the earthquake, Sean Penn brought _____ to the people of Haiti."}, {text:"Next on ESPN2, the World Series of _____."}, {text:"But before I kill you, Mr. Bond, I must show you _____."}, {text:"What gives me uncontrollable gas?"}, {text:"What do old people smell like?"}, {text:"The class field trip was completely ruined by _____."}, {text:"When Pharaoh remained unmoved, Moses called down a Plague of _____."}, {text:"What's my secret power?"}, {text:"What's there a ton of in heaven?"}, {text:"What would grandma find disturbing, yet oddly charming?"}, {text:"What did the U.S. airdrop to the children of Afghanistan?"}, {text:"What helps Obama unwind?"}, {text:"What did Vin Diesel eat for dinner?"}, {text:"_____:good to the last drop."}, {text:"Why am I sticky?"}, {text:"What gets better with age?"}, {text:"_____: kid-tested, mother-approved."}, {text:"What's the crustiest?"}, {text:"What's Teach for America using to inspire inner city students to succeed?"}, {text:"Studies show that lab rats navigate mazes 50% faster after being exposed to _____."}, {text:"Life for American Indians was forever changed when the White Man introduced them to _____."}, {text:"Make a haiku."}, {text:"I do not know with what weapons World War III will be fought, but World War IV will be fought with _____."}, {text:"Why do I hurt all over?"}, {text:"What am I giving up for Lent?"}, {text:"In Michael Jackson's final moments, he thought about _____."}, {text:"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____."}, {text:"When I am President of the United States, I will create the Department of _____."}, {text:"When I am a billionaire, I shall erect a 50-foot statue to commemorate _____."}, {text:"What's my anti-drug?"}, {text:"What never fails to liven up the party?"}, {text:"What's the new fad diet?"}, {text:"Major League Baseball has banned _____ for giving players an unfair advantage."}],
  answers: [ { text: 'Flying sex snakes.', id: 0 },
  { text: 'Michelle Obama\'s arms.', id: 1 },
  { text: 'German dungeon porn.', id: 2 },
  { text: 'White people', id: 3 },
  { text: 'Getting so angry that you pop a boner.', id: 4 },
  { text: 'Tasteful sideboob.', id: 5 },
  { text: 'Praying the gay away.', id: 6 },
  { text: 'Two midgets shitting into a bucket.', id: 7 },
  { text: 'MechaHitler.', id: 8 },
  { text: 'Being a motherfucking sorcerer.', id: 9 },
  { text: 'A disappointing birthday party.', id: 10 },
  { text: 'Puppies!', id: 11 },
  { text: 'A windmill full of corpses.', id: 12 },
  { text: 'Guys who don\'t call.', id: 13 },
  { text: 'Racially-biased SAT questions.', id: 14 },
  { text: 'Dying.', id: 15 },
  { text: 'Steven Hawking talking dirty.', id: 16 },
  { text: 'Steven Hawking talking dirty.', id: 17 },
  { text: 'Being on fire.', id: 18 },
  { text: 'A lifetime of sadness.', id: 19 },
  { text: 'An erection that lasts longer than four hours.', id: 20 },
  { text: 'AIDS', id: 21 },
  { text: 'Same-sex ice dancing.', id: 22 },
  { text: 'Glenn Beck catching his scrotum on a curtain hook.', id: 23 },
  { text: 'The Rapture.', id: 24 },
  { text: 'Pterodactyl eggs.', id: 25 },
  { text: 'Crippling debt.', id: 26 },
  { text: 'Eugenics.', id: 27 },
  { text: 'Exchanging pleasantries.', id: 28 },
  { text: 'Dying of dysentery.', id: 29 },
  { text: 'Roofies.', id: 30 },
  { text: 'Getting naked and watching Nickelodeon.', id: 31 },
  { text: 'The forbidden fruit.', id: 32 },
  { text: 'Republicans.', id: 33 },
  { text: 'The Big Bang.', id: 34 },
  { text: 'Anal beads.', id: 35 },
  { text: 'Amputees.', id: 36 },
  { text: 'Men.', id: 37 },
  { text: 'Surprise sex!', id: 38 },
  { text: 'Kim Jong-il.', id: 39 },
  { text: 'Concealing a boner.', id: 40 },
  { text: 'Agriculture.', id: 41 },
  { text: 'Glenn Beck being harried by a swarm of buzzards.', id: 42 },
  { text: 'Making a pouty face.', id: 43 },
  { text: 'A salty surprise.', id: 44 },
  { text: 'The Jews.', id: 45 },
  { text: 'Charisma.', id: 46 },
  { text: 'YOU MUST CONSTRUCT ADDITIONAL PYLONS.', id: 47 },
  { text: 'Panda sex.', id: 48 },
  { text: 'Taking off your shirt.', id: 49 },
  { text: 'A drive-by shooting.', id: 50 },
  { text: 'Ronald Reagan.', id: 51 },
  { text: 'Morgan Freeman\'s voice.', id: 52 },
  { text: 'Breaking out into song and dance.', id: 53 },
  { text: 'Jewish fraternities.', id: 54 },
  { text: 'Dead babies.', id: 55 },
  { text: 'Masturbation.', id: 56 },
  { text: 'Hormone injections.', id: 57 },
  { text: 'All-you-can-eat shrimp for $4.99.', id: 58 },
  { text: 'Incest.', id: 59 },
  { text: 'Scalping.', id: 60 },
  { text: 'Soup that is too hot.', id: 61 },
  { text: 'Nazis.', id: 62 },
  { text: 'Tom Cruise.', id: 63 },
  { text: 'Stifling a giggle at the mention of Hutus and Tutsis.', id: 64 },
  { text: 'Edible underpants.', id: 65 },
  { text: 'The Hustle.', id: 66 },
  { text: 'A Super Soaker full of cat pee.', id: 67 },
  { text: 'Figgy pudding.', id: 68 },
  { text: 'Object permanence.', id: 69 },
  { text: 'Consultants.', id: 70 },
  { text: 'Intelligent design.', id: 71 },
  { text: 'Nocturnal emissions.', id: 72 },
  { text: 'Uppercuts.', id: 73 },
  { text: 'Being marginalized.', id: 74 },
  { text: 'The profoundly handicapped.', id: 75 },
  { text: 'Obesity.', id: 76 },
  { text: 'Chutzpah.', id: 77 },
  { text: 'Unfathomable stupidity.', id: 78 },
  { text: 'Repression.', id: 79 },
  { text: 'Attitude.', id: 80 },
  { text: 'Passable transvestites.', id: 81 },
  { text: 'Party poopers.', id: 82 },
  { text: 'The American Dream.', id: 83 },
  { text: 'Child beauty pageants.', id: 84 },
  { text: 'Puberty.', id: 85 },
  { text: 'Testicular torsion.', id: 86 },
  { text: 'The folly of man.', id: 87 },
  { text: 'Nickelback.', id: 88 },
  { text: 'Swooping.', id: 89 },
  { text: 'Goats eating cans.', id: 90 },
  { text: 'The KKK.', id: 91 },
  { text: 'Kamikaze pilots.', id: 92 },
  { text: 'Horrifying laser hair removal accidents.', id: 93 },
  { text: 'Adderall.', id: 94 },
  { text: 'A look-see', id: 95 },
  { text: 'Doing the right thing.', id: 96 },
  { text: 'The taint \'the grundle\' the fleshy fun-bridge.', id: 97 },
  { text: 'The invisible hand.', id: 98 },
  { text: 'Lactation.', id: 99 },
  { text: 'Pabst Blue Ribbon.', id: 100 },
  { text: 'Powerful thighs.', id: 101 },
  { text: 'Saxophone solos.', id: 102 },
  { text: 'The gays.', id: 103 },
  { text: 'A middle-aged man on roller skates.', id: 104 },
  { text: 'A foul mouth.', id: 105 },
  { text: 'That thing that electrocutes your abs.', id: 106 },
  { text: 'Heteronormativity.', id: 107 },
  { text: 'Cuddling.', id: 108 },
  { text: 'Coat hanger abortions.', id: 109 },
  { text: 'A big hoopla about nothing.', id: 110 },
  { text: 'Boogers.', id: 111 },
  { text: 'A hot mess.', id: 112 },
  { text: 'Raptor attacks.', id: 113 },
  { text: 'My collection of high-tech sex toys.', id: 114 },
  { text: 'Fear itself.', id: 115 },
  { text: 'Bees?', id: 116 },
  { text: 'Getting drunk on mouthwash.', id: 117 },
  { text: 'Sniffing glue.', id: 118 },
  { text: 'Oversized lollipops.', id: 119 },
  { text: 'An icepick lobotomy.', id: 120 },
  { text: 'Being rich.', id: 121 },
  { text: 'Friends with benefits.', id: 122 },
  { text: 'Teaching a robot to love.', id: 123 },
  { text: 'Woman\'s suffrage.', id: 124 },
  { text: 'Me time.', id: 125 },
  { text: 'The heart of a child.', id: 126 },
  { text: 'Smallpox blankets.', id: 127 },
  { text: 'The clitoris.', id: 128 },
  { text: 'John Wilkes Booth.', id: 129 },
  { text: 'The glass ceiling.', id: 130 },
  { text: 'Sarah Palin.', id: 131 },
  { text: 'Sexy pillow fights.', id: 132 },
  { text: 'Yeast.', id: 133 },
  { text: 'Full frontal nudity.', id: 134 },
  { text: 'Parting the Red Sea.', id: 135 },
  { text: 'A Bop It.', id: 136 },
  { text: 'Michael Jackson.', id: 137 },
  { text: 'Team-building exercises.', id: 138 },
  { text: 'Harry Potter erotica.', id: 139 },
  { text: 'Authentic Mexican cuisine.', id: 140 },
  { text: 'Frolicking.', id: 141 },
  { text: 'Sexting.', id: 142 },
  { text: 'Grandma.', id: 143 },
  { text: 'Not giving a shit about the Third World.', id: 144 },
  { text: 'Licking things to claim them as your own.', id: 145 },
  { text: 'Genghis Khan.', id: 146 },
  { text: 'The hardworking Mexican.', id: 147 },
  { text: 'RoboCop.', id: 148 },
  { text: 'My relationship status.', id: 149 },
  { text: 'Scrubbing under the folds.', id: 150 },
  { text: 'Porn stars.', id: 151 },
  { text: 'Horse meat.', id: 152 },
  { text: 'Sunshine and rainbows.', id: 153 },
  { text: 'Expecting a burp and vomiting on the floor.', id: 154 },
  { text: 'Barack Obama.', id: 155 },
  { text: 'Spontaneous human combustion.', id: 156 },
  { text: 'Natural selection.', id: 157 },
  { text: 'Mouth herpes.', id: 158 },
  { text: 'Flash flooding.', id: 159 },
  { text: 'Goblins.', id: 160 },
  { text: 'A monkey smoking a cigar.', id: 161 },
  { text: 'Spectacular abs.', id: 162 },
  { text: 'A good sniff.', id: 163 },
  { text: 'Wiping her butt.', id: 164 },
  { text: 'The Three-Fifths Compromise.', id: 165 },
  { text: 'Pedophiles.', id: 166 },
  { text: 'Doin\' it in the butt.', id: 167 },
  { text: 'Being fabulous.', id: 168 },
  { text: 'Mathletes.', id: 169 },
  { text: 'Wearing underwear inside-out to avoid doing laundry.', id: 170 },
  { text: 'Nipple blades.', id: 171 },
  { text: 'An M. Night Shyamalan plot twist.', id: 172 },
  { text: 'A bag of magic beans.', id: 173 },
  { text: 'Vigorous jazz hands.', id: 174 },
  { text: 'A defective condom.', id: 175 },
  { text: 'Skeletor.', id: 176 },
  { text: 'Vikings.', id: 177 },
  { text: 'Leaving an awkward voicemail.', id: 178 },
  { text: 'Teenage pregnancy.', id: 179 },
  { text: 'Dead parents.', id: 180 },
  { text: 'Hot cheese.', id: 181 },
  { text: 'My sex life.', id: 182 },
  { text: 'A mopey zoo lion.', id: 183 },
  { text: 'Assless chaps.', id: 184 },
  { text: 'Riding off into the sunset.', id: 185 },
  { text: 'Lance Armstrong\'s missing testicle.', id: 186 },
  { text: 'Sweet, sweet vengeance.', id: 187 },
  { text: 'Genital piercings.', id: 188 },
  { text: 'Keg stands.', id: 189 },
  { text: 'Darth Vader.', id: 190 },
  { text: 'Viagra.', id: 191 },
  { text: 'Necrophilia.', id: 192 },
  { text: 'A really cool hat.', id: 193 },
  { text: 'Toni Morrison\'s vagina.', id: 194 },
  { text: 'An Oedipus complex.', id: 195 },
  { text: 'The Tempur-Pedic Swedish Sleeping System.', id: 196 },
  { text: 'Preteens.', id: 197 },
  { text: 'Dick fingers.', id: 198 },
  { text: 'A cooler full of organs.', id: 199 },
  { text: 'Shapeshifters.', id: 200 },
  { text: 'The Care Bear Stare.', id: 201 },
  { text: 'Erectile dysfunction.', id: 202 },
  { text: 'Keanu Reeves.', id: 203 },
  { text: 'The Virginia Tech Massacre.', id: 204 },
  { text: 'The Underground Railroad.', id: 205 },
  { text: 'The chronic.', id: 206 },
  { text: 'Queefing.', id: 207 },
  { text: 'Heartwarming orphans.', id: 208 },
  { text: 'A thermonuclear detonation.', id: 209 },
  { text: 'Cheating in the Special Olympics.', id: 210 },
  { text: 'Tangled Slinkys.', id: 211 },
  { text: 'A moment of silence.', id: 212 },
  { text: 'Civilian casualties.', id: 213 },
  { text: 'Catapults.', id: 214 },
  { text: 'Sharing needles.', id: 215 },
  { text: 'Ethnic cleansing.', id: 216 },
  { text: 'Emotions.', id: 217 },
  { text: 'Children on leashes.', id: 218 },
  { text: 'Balls.', id: 219 },
  { text: 'Homeless people.', id: 220 },
  { text: 'Eating all of the cookies before the AIDS bake-sale.', id: 221 },
  { text: 'Old-people smell.', id: 222 },
  { text: 'Farting and walking away.', id: 223 },
  { text: 'The inevitable heat death of the universe.', id: 224 },
  { text: 'My humps.', id: 225 },
  { text: 'The violation of our most basic human rights.', id: 226 },
  { text: 'Fingering.', id: 227 },
  { text: 'The placenta.', id: 228 },
  { text: 'The Rev. Dr. Martin Luther King, Jr.', id: 229 },
  { text: 'Leprosy.', id: 230 },
  { text: 'Sperm whales.', id: 231 },
  { text: 'Multiple stab wounds.', id: 232 },
  { text: 'Flightless birds.', id: 233 },
  { text: 'Grave robbing.', id: 234 },
  { text: 'Home video of Oprah sobbing into a Lean Cuisine.', id: 235 },
  { text: 'Oompa-Loompas.', id: 236 },
  { text: 'A murder most foul.', id: 237 },
  { text: 'Tentacle porn.', id: 238 },
  { text: 'Daddy issues.', id: 239 },
  { text: 'Bill Nye the Science Guy.', id: 240 },
  { text: 'Peeing a little bit.', id: 241 },
  { text: 'The miracle of childbirth.', id: 242 },
  { text: '\'Tweeting.\'', id: 243 },
  { text: 'Another goddamn vampire movie.', id: 244 },
  { text: 'Britney Spears at 55.', id: 245 },
  { text: 'New Age music.', id: 246 },
  { text: 'The Make-A-Wish Foundation.', id: 247 },
  { text: 'Firing a rifle into the air while balls deep in a squealing hog.',
    id: 248 },
  { text: 'Active listening.', id: 249 },
  { text: 'Nicolas Cage.', id: 250 },
  { text: '72 virgins.', id: 251 },
  { text: 'Stranger danger.', id: 252 },
  { text: 'Hope.', id: 253 },
  { text: 'A gassy antelope.', id: 254 },
  { text: 'BATMAN!!!', id: 255 },
  { text: 'Chivalry.', id: 256 },
  { text: 'Passing a kidney stone.', id: 257 },
  { text: 'Black people.', id: 258 },
  { text: 'Natalie Portman.', id: 259 },
  { text: 'A mime having a stroke.', id: 260 },
  { text: 'Classist undertones.', id: 261 },
  { text: 'Sean Penn.', id: 262 },
  { text: 'A mating display.', id: 263 },
  { text: 'The Holy Bible.', id: 264 },
  { text: 'Hot Pockets.', id: 265 },
  { text: 'A sad handjob.', id: 266 },
  { text: 'Pulling out.', id: 267 },
  { text: 'Serfdom.', id: 268 },
  { text: 'Pixelated bukkake.', id: 269 },
  { text: 'Dropping a chandelier on your enemies and riding the rope up.', id: 270 },
  { text: 'Jew-fros.', id: 271 },
  { text: 'Waiting \'til marriage.', id: 272 },
  { text: 'Euphoria by Calvin Klein.', id: 273 },
  { text: 'The World of Warcraft.', id: 274 },
  { text: 'Lunchables.', id: 275 },
  { text: 'The Kool-Aid Man.', id: 276 },
  { text: 'The Trail of Tears.', id: 277 },
  { text: 'Self-loathing.', id: 278 },
  { text: 'A falcon with a cap on its head.', id: 279 },
  { text: 'Historically black colleges.', id: 280 },
  { text: 'Not reciprocating oral sex.', id: 281 },
  { text: 'Global warming.', id: 282 },
  { text: 'Ghosts.', id: 283 },
  { text: 'World peace.', id: 284 },
  { text: 'A can of whoop-ass.', id: 285 },
  { text: 'The Dance of the Sugar Plum Fairy.', id: 286 },
  { text: 'A zesty breakfast burrito.', id: 287 },
  { text: 'Switching to Geico.', id: 288 },
  { text: 'Aaron Burr.', id: 289 },
  { text: 'Picking up girls at the abortion clinic.', id: 290 },
  { text: 'Land mines.', id: 291 },
  { text: 'Former President George W. Bush.', id: 292 },
  { text: 'Geese.', id: 293 },
  { text: 'Mutually-assured destruction.', id: 294 },
  { text: 'College.', id: 295 },
  { text: 'Date rape.', id: 296 },
  { text: 'Bling.', id: 297 },
  { text: 'A gentle caress of the inner thigh.', id: 298 },
  { text: 'A time travel paradox.', id: 299 },
  { text: 'Seppuku.', id: 300 },
  { text: 'Poor life choices.', id: 301 },
  { text: 'Waking up half-naked in a Denny\'s parking lot.', id: 302 },
  { text: 'Italians.', id: 303 },
  { text: 'GoGurt.', id: 304 },
  { text: 'Finger painting.', id: 305 },
  { text: 'Robert Downey, Jr.', id: 306 },
  { text: 'My sou.', id: 307 },
  { text: 'Smegma.', id: 308 },
  { text: 'Embryonic stem cells.', id: 309 },
  { text: 'The South.', id: 310 },
  { text: 'Christopher Walken.', id: 311 },
  { text: 'Gloryholes.', id: 312 },
  { text: 'Pretending to care.', id: 313 },
  { text: 'Public ridicule.', id: 314 },
  { text: 'A tiny horse.', id: 315 },
  { text: 'Arnold Schwarzenegger.', id: 316 },
  { text: 'A stray pube.', id: 317 },
  { text: 'Jerking off into a pool of children\'s tears.', id: 318 },
  { text: 'Child abuse.', id: 319 },
  { text: 'Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.',
    id: 320 },
  { text: 'Menstruation.', id: 321 },
  { text: 'A sassy black woman.', id: 322 },
  { text: 'Re-gifting.', id: 323 },
  { text: 'Penis envy.', id: 324 },
  { text: 'A sausage festival.', id: 325 },
  { text: 'Getting really high.', id: 326 },
  { text: 'Drinking alone.', id: 327 },
  { text: 'Too much hair gel.', id: 328 },
  { text: 'Hulk Hogan.', id: 329 },
  { text: 'Overcompensation.', id: 330 },
  { text: 'Foreskin.', id: 331 },
  { text: 'Free samples.', id: 332 },
  { text: 'Shaquille O\'Neal\'s acting career.', id: 333 },
  { text: 'Five-Dollar Footlongs.', id: 334 },
  { text: 'Whipping it out.', id: 335 },
  { text: 'A snapping turtle biting the tip of your penis.', id: 336 },
  { text: 'Muhammad (Praise Be Unto Him).', id: 337 },
  { text: 'Half-assed foreplay.', id: 338 },
  { text: 'Dental dams.', id: 339 },
  { text: 'Being a dick to children.', id: 340 },
  { text: 'Famine.', id: 341 },
  { text: 'Chainsaws for hands.', id: 342 },
  { text: 'A Gypsy curse.', id: 343 },
  { text: 'AXE Body Spray.', id: 344 },
  { text: 'The Force.', id: 345 },
  { text: 'Explosions.', id: 346 },
  { text: 'Cybernetic enhancements.', id: 347 },
  { text: 'Customer service representatives.', id: 348 },
  { text: 'White privilege.', id: 349 },
  { text: 'Gandhi.', id: 350 },
  { text: 'Road head.', id: 351 },
  { text: 'God.', id: 352 },
  { text: 'Poorly-timed Holocaust jokes.', id: 353 },
  { text: '8 oz. of sweet Mexican black-tar heroin.', id: 354 },
  { text: 'Judge Judy.', id: 355 },
  { text: 'The Little Engine That Could.', id: 356 },
  { text: 'Altar boys.', id: 357 },
  { text: 'Mr. Clean, right behind you.', id: 358 },
  { text: 'Vehicular manslaughter.', id: 359 },
  { text: 'Dwarf tossing.', id: 360 },
  { text: 'Friction.', id: 361 },
  { text: 'Lady Gaga.', id: 362 },
  { text: 'Scientology.', id: 363 },
  { text: 'Justin Bieber.', id: 364 },
  { text: 'A death ray.', id: 365 },
  { text: 'Vigilante justice.', id: 366 },
  { text: 'The Pope.', id: 367 },
  { text: 'A sea of troubles.', id: 368 },
  { text: 'Alcoholism.', id: 369 },
  { text: 'Poor people.', id: 370 },
  { text: 'A fetus.', id: 371 },
  { text: 'Women in yogurt commercials.', id: 372 },
  { text: 'Exactly what you\'d expect.', id: 373 },
  { text: 'Flesh-eating bacteria.', id: 374 },
  { text: 'My genitals.', id: 375 },
  { text: 'A balanced breakfast.', id: 376 },
  { text: 'Dick Cheney.', id: 377 },
  { text: 'Lockjaw.', id: 378 },
  { text: 'Natural male enhancement.', id: 379 },
  { text: 'Take-backsies.', id: 380 },
  { text: 'Winking at old people.', id: 381 },
  { text: 'Opposable thumbs.', id: 382 },
  { text: 'Flying sex snakes.', id: 383 },
  { text: 'Passive-aggressive Post-it notes.', id: 384 },
  { text: 'Inappropriate yodeling.', id: 385 },
  { text: 'Golden showers.', id: 386 },
  { text: 'Racism.', id: 387 },
  { text: 'Copping a feel.', id: 388 },
  { text: 'Auschwitz.', id: 389 },
  { text: 'Elderly Japanese men.', id: 390 },
  { text: 'Raping and pillaging.', id: 391 },
  { text: 'Kids with ass cancer.', id: 392 },
  { text: 'Pictures of boobs.', id: 393 },
  { text: 'The homosexual agenda.', id: 394 },
  { text: 'A homoerotic volleyball montage.', id: 395 },
  { text: 'Sexual tension.', id: 396 },
  { text: 'Hurricane Katrina.', id: 397 },
  { text: 'Fiery poops.', id: 398 },
  { text: 'Science.', id: 399 },
  { text: 'Dry heaving.', id: 400 },
  { text: 'Cards Against Humanity.', id: 401 },
  { text: 'Fancy Feast.', id: 402 },
  { text: 'A bleached asshole.', id: 403 },
  { text: 'Lumberjack fantasies.', id: 404 },
  { text: 'American Gladiators.', id: 405 },
  { text: 'Autocannibalism.', id: 406 },
  { text: 'Sean Connery.', id: 407 },
  { text: 'William Shatner.', id: 408 },
  { text: 'Domino\'s Oreo Dessert Pizza.', id: 409 },
  { text: 'An asymmetric boob job.', id: 410 },
  { text: 'Centaurs.', id: 411 },
  { text: 'A micropenis.', id: 412 },
  { text: 'Asians who aren\'t good at math.', id: 413 },
  { text: 'The milk man.', id: 414 },
  { text: 'Waterboarding.', id: 415 },
  { text: 'Wifely duties.', id: 416 },
  { text: 'Loose lips.', id: 417 },
  { text: 'The Blood of Christ.', id: 418 },
  { text: 'Actually taking candy from a baby.', id: 419 },
  { text: 'The token minority.', id: 420 },
  { text: 'Jibber-jabber.', id: 421 },
  { text: 'A brain tumor.', id: 422 },
  { text: 'Bingeing and purging.', id: 423 },
  { text: 'A clandestine butt scratch.', id: 424 },
  { text: 'The Chinese gymnastics team.', id: 425 },
  { text: 'Prancing.', id: 426 },
  { text: 'The Hamburglar.', id: 427 },
  { text: 'Police brutality.', id: 428 },
  { text: 'Man meat.', id: 429 },
  { text: 'Forgetting the Alamo.', id: 430 },
  { text: 'Eating the last known bison.', id: 431 },
  { text: 'Crystal meth.', id: 432 },
  { text: 'Booby-trapping the house to foil burglars.', id: 433 },
  { text: 'My inner demons.', id: 434 },
  { text: 'Third base.', id: 435 },
  { text: 'Soiling oneself.', id: 436 },
  { text: 'Laying an egg.', id: 437 },
  { text: 'Giving 110%.', id: 438 },
  { text: 'Hot people.', id: 439 },
  { text: 'Friendly fire.', id: 440 },
  { text: 'Count Chocula.', id: 441 },
  { text: 'Pac-Man uncontrollably guzzling cum.', id: 442 },
  { text: 'Estrogen.', id: 443 },
  { text: 'My vagina.', id: 444 },
  { text: 'Kanye West.', id: 445 },
  { text: 'A robust mongoloid.', id: 446 },
  { text: 'The Donald Trump Seal of Approval.', id: 447 },
  { text: 'The true meaning of Christmas.', id: 448 },
  { text: 'Her Royal Highness, Queen Elizabeth II.', id: 449 },
  { text: 'An honest cop with nothing left to lose.', id: 450 },
  { text: 'Feeding Rosie O\'Donnell.', id: 451 },
  { text: 'The Amish.', id: 452 },
  { text: 'The terrorists.', id: 453 },
  { text: 'When you fart and a little bit comes out.', id: 454 },
  { text: 'Pooping back and forth. Forever.', id: 455 },
  { text: 'Friends who eat all the snacks.', id: 456 },
  { text: 'Cockfights.', id: 457 },
  { text: 'Bitches.', id: 458 },
  { text: 'Seduction.', id: 459 } ]
}
